### ISSUE TITLE
what is ```- failed prototype test execution```

### ISSUE THREAD

**Issue by Kingkhan14** [abrahamjuliot/creepjs#249]
how its getting determined in a proxied object 

```- failed prototype test execution```

**Comment by abrahamjuliot** [comment]
It means that the test silently failed to complete due to an unforeseen error.

**Comment by Kingkhan14** [comment]
like which error bro any examples

**Comment by abrahamjuliot** [comment]
It can be any error produced by the client. There should be none. Are you seeing `- failed prototype test execution` in a clean browser?

**Comment by Kingkhan14** [comment]
no only when using proxied object

**Comment by Kingkhan14** [comment]
```
get(target, ctx) {
                var methods = ["call", "bind", "apply", "toString", "string"];
                if(methods.includes(ctx)) {
                    return target[ctx].bind(target);
                } else if(typeof ctx === 'symbol') {
                    return target[ctx];
                } else {
                    return target.bind(target);
                }
            }
```
like this when using proxy

**Comment by abrahamjuliot** [comment]
I see. It's likely a side effect of the way that proxy object is written. I have no solution, but you can run the test script and log the error. Let's leave the issue open. I will set a task to log this error to the console.

**Comment by Kingkhan14** [comment]
Ok will update

**Comment by flen201** [comment]
i believe 
```
Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
    at Reflect.setPrototypeOf (<anonymous>)
    at Object.setPrototypeOf (<anonymous>:361:46)
    at Function.setPrototypeOf (<anonymous>)
    at getNullConversionTypeErrorLie (https://example.com/test.js:189:12)
    at getLies (https://minimappers.com/test.js:534:39)
    at https://minimappers.com/test.js:649:15
    at Array.forEach (<anonymous>)
    at searchLies (https://example.com/test.js:600:18)
    at getPrototypeLies (https://example.com/test.js:729:3)
    at https://example.com/test.js:772:58
```

this causing the issue

**Comment by flen201** [comment]
specifically this error happens only when the proxied is property like `Navigator.prototype.platform` but proxying other functions like `Element.prototype.setAttribute` not causing any errors
